version: '3'

services:
  web:
    build:
      context: ./docker/web/nginx
      dockerfile: ./Dockerfile
    ports:
      - ${WEB_PORT:-8000}:80
    volumes:
#      - ./docker/web/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#      - ./docker/web/nginx/volumes/log:/var/log/nginx
      - ./src/public:/var/www/html/public
    links:
      - app
  app:
    build:
      context: .
      dockerfile: ./docker/app/php-fpm/Dockerfile
    volumes:
      - ./src:/var/www/html:cached
    links:
#      - db
      - smtp
#  db:
#    build:
#      context: ./docker/db/mysql
#      dockerfile: ./Dockerfile
#    volumes:
#      - ./docker/db/mysql/volumes/data:/var/lib/mysql
#      - ./docker/db/mysql/volumes/log:/var/log
#    ports:
#      - ${DB_PORT:-33060}:3306
  smtp:
    build: ./docker/smtp/mailhog
    ports:
      - ${SMTP_PORT:-8025}:8025